<?php
/**
 * @category   Linh
 * @package    Linh_Demo
 * @author     hoanglinh.08122000@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Linh\Demo\Model\ResourceModel;

class Demo extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('linh_demo', 'demo_id');   //here "linh_demo" is table name and "demo_id" is the primary key of custom table
    }
}