<?php
/**
 * @category   Table
 * @package    Table_Table
 * @author     hoanglinh.08122000@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Table\Table\Model;

use Magento\Framework\Model\AbstractModel;

class Table extends AbstractModel
{
    /**
     * Define resource model
     */
    protected function _construct()
    {
        $this->_init('Table\Table\Model\ResourceModel\Table');
    }
}